import { expect, test, type Page } from '@playwright/test';
import { installCloudApiMock, selectDestinationCity } from './cloud';

function dateOffset(days:number){const date=new Date();date.setDate(date.getDate()+days);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
async function createTrip(page:Page,name:string,start:string,end:string){await page.getByRole('button',{name:'新建旅行'}).first().click();await page.getByLabel('旅行名称').fill(name);await selectDestinationCity(page, '上海');await page.getByLabel('出发地').fill('杭州');await page.getByLabel('出发日期').fill(start);await page.getByLabel('返程日期').fill(end);await page.getByLabel('旅行时区').fill(Intl.DateTimeFormat().resolvedOptions().timeZone);await page.getByRole('button',{name:'创建旅行'}).click();}

test('keeps trip management reachable and edits itinerary without viewport or history surprises',async({page},testInfo)=>{
 test.skip(testInfo.project.name!=='mobile-390','iPhone-sized usability flow');await installCloudApiMock(page);await page.goto('/login');await page.getByLabel('邮箱地址').fill('e2e@example.com');await page.getByLabel('密码').fill('password123');await page.getByRole('button',{name:'登录 TripFlow'}).click();
 const today=dateOffset(0);await createTrip(page,'移动测试旅行',today,today);await expect(page).toHaveURL(/\/today$/);await page.getByRole('link',{name:'我的旅行',exact:true}).click();await expect(page.getByRole('heading',{name:'我的旅行'})).toBeVisible();
 const tomorrow=dateOffset(1);await createTrip(page,'待删除旅行',tomorrow,tomorrow);await expect(page).toHaveURL(/\/overview$/);await page.getByRole('link',{name:'我的旅行',exact:true}).click();await expect(page.getByRole('heading',{name:'待删除旅行'})).toBeVisible();await page.getByLabel('删除旅行：待删除旅行').click();await page.getByRole('button',{name:'确认删除'}).click();await expect(page.getByRole('heading',{name:'待删除旅行'})).not.toBeVisible();
 await page.getByRole('link',{name:'旅行总览',exact:true}).click();await page.getByLabel('选择当前旅行').selectOption({label:'移动测试旅行'});await page.goto('/today');await page.getByRole('link',{name:'行程',exact:true}).click();await expect(page).toHaveURL(/\/itinerary$/);await page.getByRole('button',{name:'添加安排'}).first().click();const place=page.getByLabel('地点名称');await place.focus();expect(await place.evaluate(element=>getComputedStyle(element).fontSize)).toBe('16px');expect(await page.evaluate(()=>window.visualViewport?.scale??1)).toBe(1);await page.getByRole('button',{name:'取消'}).click();await expect(place).not.toBeVisible();expect(await page.evaluate(()=>window.innerWidth)).toBe(390);expect(await page.evaluate(()=>window.visualViewport?.scale??1)).toBe(1);await expect(page).toHaveURL(/\/itinerary$/);
 await page.getByRole('button',{name:'添加安排'}).first().click();await page.getByLabel('时间（可选）').fill('10:30');await page.getByLabel('地点名称').fill('旧地点');await page.getByPlaceholder('用于调用外部地图导航').fill('旧地址');await page.getByLabel('预计停留（分钟）').fill('45');await page.getByLabel('备注').fill('旧备注');await page.getByRole('button',{name:'添加行程'}).click();await page.getByLabel('编辑行程：旧地点').click();await expect(page).toHaveURL(/\/itinerary$/);const editor=page.getByRole('region',{name:'编辑行程：旧地点'});await editor.getByLabel('时间（可选）').fill('11:45');await editor.getByLabel('地点名称').fill('新地点');await editor.getByPlaceholder('用于调用外部地图导航').fill('上海市新地址');await editor.getByLabel('预计停留（分钟）').fill('90');await editor.getByLabel('备注').fill('新备注');await editor.getByLabel('状态').selectOption('completed');await editor.getByRole('button',{name:'保存修改'}).click();await expect(page.getByText('新地点',{exact:true})).toBeVisible();await expect(page.getByText('上海市新地址',{exact:true})).toBeVisible();
 await page.reload();await expect(page.getByText('新地点',{exact:true})).toBeVisible();await expect(page.getByText('11:45',{exact:true})).toBeVisible();await page.getByLabel('编辑行程：新地点').click();await page.getByRole('button',{name:'返回行程'}).click();await expect(page.getByRole('heading',{name:'行程'})).toBeVisible();await expect(page).toHaveURL(/\/itinerary$/);
});
