import { expect, test } from '@playwright/test';
import { installCloudApiMock } from './cloud';
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
test('supports active-trip Today quick actions and offline UI on mobile',async({page,context},testInfo)=>{
 test.skip(testInfo.project.name!=='mobile-390','mobile travel mode');await installCloudApiMock(page);await page.goto('/login');await page.getByLabel('邮箱地址').fill('e2e@example.com');await page.getByLabel('密码').fill('password123');await page.getByRole('button',{name:'登录 TripFlow'}).click();
 await page.getByRole('button',{name:'新建旅行'}).first().click();await page.getByLabel('旅行名称').fill('今天的旅行');await page.getByLabel('目的地').fill('上海');await page.getByLabel('出发地').fill('杭州');const today=localDate();await page.getByLabel('出发日期').fill(today);await page.getByLabel('返程日期').fill(today);await page.getByLabel('旅行时区').fill(Intl.DateTimeFormat().resolvedOptions().timeZone);await page.getByRole('button',{name:'创建旅行'}).click();await page.goto('/trips');await page.getByLabel('查看今天的旅行今天').click();await expect(page.getByRole('heading',{name:/今天 · 上海/})).toBeVisible();
 await page.getByRole('button',{name:'快速加行程'}).click();await page.getByLabel('地点名称').fill('外滩');await page.getByPlaceholder('用于调用外部地图导航').fill('上海市中山东一路');await page.getByRole('button',{name:'添加行程'}).click();await expect(page.getByText('外滩').first()).toBeVisible();await expect(page.getByLabel('导航到外滩')).toHaveAttribute('href',/google\.com\/maps/);await page.getByRole('button',{name:'完成'}).click();await expect(page.getByText('已完成')).toBeVisible();
 await page.getByRole('button',{name:'快速记消费'}).click();await page.getByLabel('消费名称').fill('早餐');await page.getByLabel('消费金额').fill('28');await page.getByRole('button',{name:'添加',exact:true}).click();await page.getByRole('link',{name:'归档',exact:true}).click();await expect(page.getByText('早餐')).toBeVisible();
 await page.evaluate(()=>navigator.serviceWorker.ready.then(()=>true));await context.setOffline(true);await expect(page.getByText(/当前离线，无法获取最新数据/).first()).toBeVisible();await page.reload();await expect(page.getByText(/当前离线，无法获取最新数据/).first()).toBeVisible();await context.setOffline(false);
});
