import { Check, Heart, Pencil, Plus, Star, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useParams, useSearchParams } from 'react-router-dom';
import { ExpenseForm, JournalForm, MediaForm, PurchaseForm } from '../components/archive/ArchiveForms';
import { ConfirmDialog } from '../components/ui/ConfirmDialog';
import { DataLoadingState } from '../components/ui/DataLoadingState';
import { NoTripState } from '../components/ui/NoTripState';
import { PageHeader } from '../components/ui/PageHeader';
import { categoryTotals, expenseCategoryLabels, formatMoney, mediaTypeLabels, totalsByCurrency } from '../domain/archive';
import { formatDayDate } from '../lib/formatters';
import { useArchive } from '../state/useArchive';
import { useTrips } from '../state/useTrips';
import type { Expense, Journal, MediaNote, Purchase } from '../types/archive';

type Tab='expenses'|'purchases'|'media'|'journals';
const tabs: {id:Tab;label:string}[]=[{id:'expenses',label:'消费'},{id:'purchases',label:'购物'},{id:'media',label:'素材'},{id:'journals',label:'日记'}];
type Editing = {kind:Tab; item?: Expense|Purchase|MediaNote|Journal; dayId?:string} | null;
type Deleting = {kind:Tab; id:string; name:string} | null;

export function ArchivePage(){
 const {selectedTrip,updateTrip,trips,selectTrip}=useTrips(); const archive=useArchive(); const [params,setParams]=useSearchParams(); const {tripId}=useParams();
 const raw=params.get('tab'); const tab=tabs.some(x=>x.id===raw)?raw as Tab:'expenses';
 const [editing,setEditing]=useState<Editing>(null); const [deleting,setDeleting]=useState<Deleting>(null);
 useEffect(()=>{if(tripId&&trips.some(x=>x.id===tripId)&&selectedTrip?.id!==tripId)selectTrip(tripId);},[selectTrip,selectedTrip?.id,tripId,trips]);
 if(!selectedTrip)return <NoTripState/>;
 const trip=selectedTrip;
 async function remove(){if(!deleting)return;const fn={expenses:archive.deleteExpense,purchases:archive.deletePurchase,media:archive.deleteMediaNote,journals:archive.deleteJournal}[deleting.kind];await fn(deleting.id);setDeleting(null);}
 return <section>
  <PageHeader eyebrow={`After the trip · ${trip.destination}`} title="旅行归档" description="整理旅行中的花费、购物、素材线索与每日记录。" action={<button type="button" disabled={archive.isSaving} onClick={()=>setEditing({kind:tab})} className="inline-flex items-center gap-2 rounded-xl bg-ink px-4 py-2.5 text-sm font-semibold text-white"><Plus className="size-4"/>新增{tabs.find(x=>x.id===tab)?.label}</button>}/>
  <nav aria-label="归档分类" className="mt-7 grid grid-cols-4 gap-1 rounded-2xl border border-line bg-white p-1 shadow-card">{tabs.map(x=><button type="button" key={x.id} onClick={()=>{setParams({tab:x.id});setEditing(null)}} className={`rounded-xl px-2 py-2.5 text-sm font-semibold ${tab===x.id?'bg-ink text-white':'text-muted hover:bg-canvas'}`}>{x.label}</button>)}</nav>
  {archive.error?<div role="alert" className="mt-5 flex justify-between gap-3 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><span>{archive.error}</span><button type="button" onClick={archive.clearError}>关闭</button></div>:null}
  {editing?.kind===tab?<Editor editing={editing} trip={trip} archive={archive} close={()=>setEditing(null)}/>:null}
  {archive.isLoading?<DataLoadingState/>:tab==='expenses'?<Expenses trip={trip} expenses={archive.expenses} busy={archive.isSaving} edit={x=>setEditing({kind:'expenses',item:x})} remove={x=>setDeleting({kind:'expenses',id:x.id,name:x.title})} updateTrip={updateTrip}/>:tab==='purchases'?<Purchases items={archive.purchases} busy={archive.isSaving} edit={x=>setEditing({kind:'purchases',item:x})} remove={x=>setDeleting({kind:'purchases',id:x.id,name:x.title})} toggle={x=>archive.savePurchase({...x,organized:!x.organized},x)}/>:tab==='media'?<Media items={archive.mediaNotes} trip={trip} busy={archive.isSaving} edit={x=>setEditing({kind:'media',item:x})} remove={x=>setDeleting({kind:'media',id:x.id,name:x.filename})} toggle={x=>archive.saveMediaNote({...x,favorite:!x.favorite},x)}/>:<Journals items={archive.journals} trip={trip} edit={x=>setEditing({kind:'journals',item:x})} add={dayId=>setEditing({kind:'journals',dayId})} remove={x=>setDeleting({kind:'journals',id:x.id,name:'当天日记'})}/>}
  <ConfirmDialog open={!!deleting} title="确认删除？" description={`“${deleting?.name??''}”删除后无法恢复。`} busy={archive.isSaving} onCancel={()=>setDeleting(null)} onConfirm={()=>void remove().catch(()=>undefined)}/>
 </section>;
}

function Editor({editing,trip,archive,close}:{editing:NonNullable<Editing>;trip:NonNullable<ReturnType<typeof useTrips>['selectedTrip']>;archive:ReturnType<typeof useArchive>;close():void}){
 if(editing.kind==='expenses')return <ExpenseForm trip={trip} item={editing.item as Expense|undefined} busy={archive.isSaving} onCancel={close} onSubmit={async v=>{await archive.saveExpense(v,editing.item as Expense|undefined);close()}}/>;
 if(editing.kind==='purchases')return <PurchaseForm trip={trip} item={editing.item as Purchase|undefined} busy={archive.isSaving} onCancel={close} onSubmit={async v=>{await archive.savePurchase(v,editing.item as Purchase|undefined);close()}}/>;
 if(editing.kind==='media')return <MediaForm trip={trip} item={editing.item as MediaNote|undefined} busy={archive.isSaving} onCancel={close} onSubmit={async v=>{await archive.saveMediaNote(v,editing.item as MediaNote|undefined);close()}}/>;
 return <JournalForm trip={trip} item={editing.item as Journal|undefined} dayId={editing.dayId} busy={archive.isSaving} onCancel={close} onSubmit={async v=>{await archive.saveJournal(v,editing.item as Journal|undefined);close()}}/>;
}

function Empty({children}:{children:string}){return <div className="mt-6 rounded-3xl border border-dashed border-line bg-white py-14 text-center text-sm text-muted">{children}</div>}
function IconButtons({onEdit,onDelete}:{onEdit():void;onDelete():void}){return <div className="flex gap-1"><button type="button" aria-label="编辑" onClick={onEdit} className="grid size-9 place-items-center rounded-lg text-muted hover:bg-canvas"><Pencil className="size-4"/></button><button type="button" aria-label="删除" onClick={onDelete} className="grid size-9 place-items-center rounded-lg text-muted hover:bg-red-50 hover:text-red-600"><Trash2 className="size-4"/></button></div>}
function MoneyList({totals}:{totals:Record<string,number>}){return <>{Object.entries(totals).map(([currency,total])=><span key={currency} className="block tabular-nums">{currency} {formatMoney(total,currency)}</span>)}</>}

function Expenses({trip,expenses,busy,edit,remove,updateTrip}:{trip:NonNullable<ReturnType<typeof useTrips>['selectedTrip']>;expenses:Expense[];busy:boolean;edit(x:Expense):void;remove(x:Expense):void;updateTrip:ReturnType<typeof useTrips>['updateTrip']}){
 const totals=totalsByCurrency(expenses),categories=categoryTotals(expenses); const [budgetOpen,setBudgetOpen]=useState(false); const [amount,setAmount]=useState(trip.budgetAmount??0);const [currency,setCurrency]=useState(trip.budgetCurrency??'CNY');const [saving,setSaving]=useState(false);
 const counted=trip.budgetCurrency?totals[trip.budgetCurrency]??0:0; const remaining=(trip.budgetAmount??0)-counted;const other=trip.budgetCurrency&&Object.keys(totals).some(x=>x!==trip.budgetCurrency);
 return <>
  <div className="mt-6 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-line bg-white p-5 shadow-card"><p className="text-xs font-bold text-muted">总消费</p><div className="mt-2 text-xl font-bold"><MoneyList totals={totals}/>{Object.keys(totals).length===0?'暂无消费':null}</div></article><article className="rounded-2xl border border-line bg-white p-5 shadow-card"><div className="flex justify-between"><p className="text-xs font-bold text-muted">旅行预算</p><button type="button" onClick={()=>setBudgetOpen(!budgetOpen)} className="text-xs font-semibold text-brand">{trip.budgetAmount===null?'设置':'修改'}</button></div><p className="mt-2 text-xl font-bold">{trip.budgetAmount===null?'未设置':`${trip.budgetCurrency} ${formatMoney(trip.budgetAmount,trip.budgetCurrency!)}`}</p></article><article className="rounded-2xl border border-line bg-white p-5 shadow-card"><p className="text-xs font-bold text-muted">{remaining>=0?'剩余预算':'已超支'}</p><p className={`mt-2 text-xl font-bold ${remaining<0?'text-red-600':'text-brand'}`}>{trip.budgetAmount===null?'—':formatMoney(Math.abs(remaining),trip.budgetCurrency!)}</p>{trip.budgetAmount!==null?<div className="mt-3 h-2 overflow-hidden rounded-full bg-line"><div className="h-full bg-brand" style={{width:`${Math.min(100,(counted/trip.budgetAmount)*100||0)}%`}}/></div>:null}{other?<p className="mt-3 text-xs text-amber-700">另有其他币种消费未计入当前预算。</p>:null}</article></div>
  {budgetOpen?<form onSubmit={e=>{e.preventDefault();if(saving)return;setSaving(true);void updateTrip(trip.id,{budgetAmount:amount,budgetCurrency:currency.toUpperCase()}).then(()=>setBudgetOpen(false)).finally(()=>setSaving(false))}} className="mt-4 flex flex-col gap-3 rounded-2xl border border-brand/20 bg-brand-soft/50 p-4 sm:flex-row sm:items-end"><label className="flex-1"><span className="field-label">预算金额</span><input aria-label="预算金额" type="number" min="0" step="0.01" required value={amount} onChange={e=>setAmount(Number(e.target.value))} className="field-input"/></label><label className="sm:w-40"><span className="field-label">预算币种</span><input aria-label="预算币种" maxLength={3} pattern="[A-Za-z]{3}" required value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())} className="field-input"/></label><button disabled={saving||busy} className="rounded-xl bg-ink px-5 py-2.5 text-sm font-semibold text-white">{saving?'保存中…':'保存预算'}</button></form>:null}
  <h2 className="mt-8 text-lg font-bold">分类统计</h2><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{Object.entries(expenseCategoryLabels).map(([key,label])=><article key={key} className="rounded-2xl border border-line bg-white p-4"><p className="text-xs text-muted">{label}</p><p className="mt-2 text-sm font-bold"><MoneyList totals={categories[key]??{}}/>{!categories[key]?'—':null}</p></article>)}</div>
  <h2 className="mt-8 text-lg font-bold">消费记录</h2>{expenses.length?<div className="mt-3 overflow-hidden rounded-3xl border border-line bg-white shadow-card">{[...expenses].sort((a,b)=>b.date.localeCompare(a.date)).map((x,i)=><article key={x.id} className={`flex items-center gap-3 p-4 sm:p-5 ${i?'border-t border-line':''}`}><div className="min-w-0 flex-1"><p className="font-semibold">{x.title}</p><p className="mt-1 text-xs text-muted">{x.date} · {expenseCategoryLabels[x.category]}{x.notes?` · ${x.notes}`:''}</p></div><p className="shrink-0 font-bold tabular-nums">{x.currency} {formatMoney(x.amount,x.currency)}</p><IconButtons onEdit={()=>edit(x)} onDelete={()=>remove(x)}/></article>)}</div>:<Empty>还没有消费记录</Empty>}
 </>;
}

function Purchases({items,busy,edit,remove,toggle}:{items:Purchase[];busy:boolean;edit(x:Purchase):void;remove(x:Purchase):void;toggle(x:Purchase):Promise<void>}){return items.length?<div className="mt-6 grid gap-4 lg:grid-cols-2">{items.map(x=><article key={x.id} className="rounded-2xl border border-line bg-white p-5 shadow-card"><div className="flex gap-3"><div className="min-w-0 flex-1"><p className="font-bold">{x.title}</p><p className="mt-1 text-xs text-muted">{x.date}{x.location?` · ${x.location}`:''}{x.recipient?` · 给 ${x.recipient}`:''}</p><p className="mt-3 font-semibold">{x.currency} {formatMoney(x.amount,x.currency)}</p></div><IconButtons onEdit={()=>edit(x)} onDelete={()=>remove(x)}/></div><button disabled={busy} type="button" onClick={()=>void toggle(x).catch(()=>undefined)} className={`mt-4 inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-semibold ${x.organized?'bg-brand-soft text-brand':'bg-stone-100 text-muted'}`}><Check className="size-3.5"/>{x.organized?'已整理':'未整理'}</button></article>)}</div>:<Empty>还没有购物记录</Empty>}
function Media({items,trip,busy,edit,remove,toggle}:{items:MediaNote[];trip:NonNullable<ReturnType<typeof useTrips>['selectedTrip']>;busy:boolean;edit(x:MediaNote):void;remove(x:MediaNote):void;toggle(x:MediaNote):Promise<void>}){return items.length?<div className="mt-6 grid gap-4 lg:grid-cols-2">{items.map(x=>{const day=trip.days.find(d=>d.id===x.tripDayId),it=trip.itineraryItems.find(i=>i.id===x.itineraryItemId);return <article key={x.id} className="rounded-2xl border border-line bg-white p-5 shadow-card"><div className="flex gap-3"><div className="min-w-0 flex-1"><p className="font-bold">{x.filename}</p><p className="mt-1 text-xs text-muted">{mediaTypeLabels[x.mediaType]}{day?` · Day ${day.dayNumber}`:''}{it?` · ${it.placeName}`:''}</p>{x.notes?<p className="mt-3 text-sm text-muted">{x.notes}</p>:null}</div><IconButtons onEdit={()=>edit(x)} onDelete={()=>remove(x)}/></div><button disabled={busy} type="button" onClick={()=>void toggle(x).catch(()=>undefined)} className={`mt-4 inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-semibold ${x.favorite?'bg-amber-50 text-amber-700':'bg-stone-100 text-muted'}`}><Heart className={`size-3.5 ${x.favorite?'fill-current':''}`}/>{x.favorite?'已精选':'标记精选'}</button></article>})}</div>:<Empty>还没有素材备注</Empty>}
function Journals({items,trip,edit,add,remove}:{items:Journal[];trip:NonNullable<ReturnType<typeof useTrips>['selectedTrip']>;edit(x:Journal):void;add(dayId:string):void;remove(x:Journal):void}){return <div className="mt-6 space-y-4">{trip.days.map(day=>{const x=items.find(j=>j.tripDayId===day.id);return <article key={day.id} className="rounded-2xl border border-line bg-white p-5 shadow-card"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><p className="text-xs font-bold text-brand">DAY {day.dayNumber} · {formatDayDate(day.date)}</p>{x?<><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{x.content}</p>{x.rating?<p aria-label={`${x.rating} 星`} className="mt-3 flex text-amber-500">{Array.from({length:x.rating},(_,i)=><Star key={i} className="size-4 fill-current"/>)}</p>:null}</>:<p className="mt-3 text-sm text-muted">这一天还没有日记。</p>}</div>{x?<IconButtons onEdit={()=>edit(x)} onDelete={()=>remove(x)}/>:<button type="button" onClick={()=>add(day.id)} className="rounded-xl border border-line px-3 py-2 text-xs font-semibold">写日记</button>}</div></article>})}</div>}
